### ISSUE TITLE
type definitions not known

### ISSUE THREAD

**Issue by JoostdeGussem** [ddegras/sparseGFL#1]
What are the definitions of the types
mat    (a 2 dimensional array?)
cube  (a 3 dimensional array?)
uword  (an integer?)
in the allmethods.cpp?

**Comment by ddegras** [comment]
It’s part of the C++ library Armadillo.
If you compile the script/whole package with RcppArmadillo installed, things should go smoothly.


David Degras
Assistant Professor
Department of Mathematics
University of Massachusetts Boston
web: um-boston.academia.edu/DavidDegras<http://um-boston.academia.edu/DavidDegras>



On Feb 3, 2020, at 11:10 AM, JoostdeGussem <notifications@github.com<mailto:notifications@github.com>> wrote:


[EXTERNAL SENDER]

What are the definitions of the types
mat
cube
word
in the allmethods.cpp?
