### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jamesdalg** [ddegras/sparseGFL#2]
I've tested out your spatiotemporal lasso, and it is fantastically fast. Two questions:
1. Using the below code, how does one actually plot out the results? I see the beta matrix there, in the results, after this code, but it's not conformable with the X matrix, so unlike the genlasso package... I can't exactly plot the results.
`
```
m <- 5   # number of (time-varying) observation variables
n <- 100 # time series length
p <- 10  # number of (time-varying) predictor variables 

x <- array(rnorm(m*n*p),c(m,p,n)) # random coefficients
beta <- matrix(0,p,n) # random coefficients with 50% sparsity  
beta[1:5,1:50] <- runif(5) # and one change point at time 51
beta[6:p,51:n] <- runif(5)
y <- matrix(,m,n)
for (i in 1:n){ y[,i] <- x[,,i] %*% beta[,i] + rnorm(m,sd=.01)}

lambda1 <- .05
lambda2 <- 1.5
alpha <- .9

 result <- SGFL(x, y, lambda1, lambda2, alpha, 
	intercept=FALSE, verbose=TRUE)
```

`
2. Is there an example that uses parallelization? Does one do this with SNOW?

**Comment by ddegras** [comment]
Glad you're finding the package helpful.
1. Would this do the trick?  
`matplot(t(result$beta), type = "l", xlab = "Time", ylab = "Beta")`
2. You can for example use `foreach` and `doParSNOW`. I usually do `foreach` and `doParallel` but any parallel backend compatible with `foreach` works. Here's an example (following with your example). 
```
library(foreach)
library(doSNOW)
cl <- makeCluster(2, type="SOCK")
registerDoSNOW(cl)
result <- SGFL(x, y, lambda1, lambda2, alpha,
	intercept=FALSE, parallel = TRUE)
```

**Comment by jamesdalg** [comment]
That works! Thanks!
